version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: .docker/api/dev.Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./api:/go/src/github.com/blyndusk/repo-template/api
    networks:
      - main

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main

  adminer:
    build:
      context: .
      dockerfile: .docker/adminer/Dockerfile
    environment: 
      ADMINER_DB: db
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: root
      ADMINER_SERVER: postgres
      ADMINER_USERNAME: root
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Books search DB
    restart: always
    ports:
      - 3334:8080
    depends_on:
      - postgres
    networks:
      - main

volumes:
  postgres:

networks:
  main:
