name: "[CI] GO"

on:
  push:
    branches:
      - '**'
    paths:
      - '**/*.go'
      - '**/go.*'


jobs:
  GO:
    name: GO
    runs-on: ubuntu-latest
    steps:
      # checkout to current workspace
    - name: 1 - CHECKOUT
      uses: actions/checkout@v2

      # install golang with specific version
    - name: 2 - SETUP GO@1.15
      uses:  actions/setup-go@v1
      with:
          go-version: 1.15

      # cache go modules to make the build faster
    - name: 3 - CACHE GO MODULES
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

      # lint files before build using gofmt
    - name: 4 - LINT
      run: |
        gofmt -e -l -s -w .
    
      # build the project (in the api/ folder L11)
    - name: 5 - BUILD
      run: |
        go build -v ./...