name: DOCKER

on:
  push:
    branches:
      - main

jobs:
  DOCKER:
    name: DOCKER
    runs-on: ubuntu-latest
    steps:
        # checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v2

        # login to container registry
      - name: 2 - LOGIN TO GHCR.IO
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # build and push the app with given file and tag
      - name: 3 - BUILD + PUSH
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: .docker/api/prod.Dockerfile
          tags: ghcr.io/blyndusk/repo-template_api:latest

        # output the logs
      - name: 4 - IMAGE DIGEST
        run: echo ${{ steps.docker_build.outputs.digest }}
